### ISSUE TITLE
Can't install Flubber in gradle

### ISSUE THREAD

**Issue by mridah** [Appolica/Flubber#10]
when I paste the given line in my app gradle, it gives the following error:

> It looks like you are trying to substitute a version variable, but using single quotes('). For groovy string....

When I type: `compile "com.appolica:flubber:$LATEST_LIB_VERSION"`, it gives the following error:

> Error:(63, 0) Could not get unknown property 'LATEST_LIB_VERSION' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler

How do I use this library ?? @ralito @rokn @mmarkov-appolica @deangenovski @bkolarov-appolica

**Comment by haneef5k** [comment]
@mridah go to below link
https://bintray.com/appolica-ltd/appolica/Flubber/1.0.1
Current Gradle Version : compile 'com.appolica:flubber:1.0.1'

**Comment by deangenovski** [comment]
@haneef5k is correct. The $LATEST_LIB_VERSION is just a place holder you will have to replace it with the latest version from bintray. The latest version can be fetched with `compile 'com.appolica:flubber:1.0.1'`
